### ISSUE TITLE
Add Progress Indicator Widgets

### ISSUE THREAD

**Issue by c-mart** [Orasund/elm-ui-widgets#11]
Add Progress Indicator widgets from the Material Design [specification](https://material.io/components/progress-indicators).

How are other Elm projects doing animation for progress indicators?

- There is [elm-spinner](https://package.elm-lang.org/packages/damienklinnert/elm-spinner/latest/). It is super configurable but it comes with a bunch of "wiring" that you need to update through the runtime.
- [elm-style-framework](https://github.com/lucamug/elm-style-framework) implements [spinners](https://github.com/lucamug/elm-style-framework/blob/master/src/Framework/Spinner.elm) as SVGs defined with the Elm [Svg](https://package.elm-lang.org/packages/elm/svg/latest/) package. The animation is baked into the SVG, so the rest of the app doesn't need to care about it. I like how simple it is to integrate these.

So, Indeterminate indicators appear very easy (just show an animated SVG). For Determinate indicators, the function could probably take a `Float` between 0 and 1 (or maybe an `Int` between 0 and 100), and use this as a parameter to indicate appropriate progress in the SVG.

I can probably implement this unless @Orasund has other ideas. In Exosphere, we are [trying](https://gitlab.com/exosphere/exosphere/-/issues/357#) to discontinue use of elm-style-framework, and this would help get us there. :)

**Comment by Orasund** [comment]
I think for now SVG is perfectly fine. So please, go ahead.

For the future i'd like the animations to be compatible with [elm-animator](https://package.elm-lang.org/packages/mdgriffith/elm-animator/latest/).

**Comment by Orasund** [comment]
If you add a PR you will hopefully see a checklist that you can follow along.

Please try to stick to the material design specification where ever possible and add comments whenever you don't.

If you need any help, just ask.

**Comment by Orasund** [comment]
Thanks for your contribution. I really like how this turned out. I've just published version 2.1.0 that contains your widget ;)
