### ISSUE TITLE
Button text font color: Can't override

### ISSUE THREAD

**Issue by julianpistorius** [Orasund/elm-ui-widgets#12]
In our app we currently have a blue button with a white text label. I am trying to replace it with the `Widget.button` from this package. I have two problems:

## Problem 1: There does not seem to be a way to override the calculated font color 

In particular it's black on this particular shade of blue, and I can't override it to white.

![Screen Shot 2020-07-14 at 10 55 28](https://user-images.githubusercontent.com/742633/87722813-4ab48880-c7a8-11ea-81df-57415cac8490.png)

## Problem 2: Font color calculation is different from Material Design spec

The [calculation for determining the font color](https://github.com/Orasund/elm-ui-widgets/blob/b509e632735cd58fdedb7fc59c72e2044f3864cd/src/Widget/Style/Material.elm#L292) is different from the Material Design accessibility guidelines. In particular the elm-ui-widgets calculation returns black where Material Design specifies white.

I used this Material Design color picker: https://material.io/design/color/the-color-system.html#tools-for-picking-colors

It seems the [`Color.Accessibility.maximumContrast` function](https://github.com/noahzgordon/elm-color-extra/blob/60e9c3be28e34129f3e11ec7e826bc337666fe60/src/Color/Accessibility.elm#L77) in the `noahzgordon/elm-color-extra` package is closer to the Material Design one.

I made an Ellie to demonstrate this: https://ellie-app.com/9rCXqGM8BX4a1

![Screen Shot 2020-07-16 at 14 03 44](https://user-images.githubusercontent.com/742633/87723120-d6c6b000-c7a8-11ea-94b9-0d5d779b5a44.png)

The three columns of buttons are:

- **Elm UI Widgets:** Widget.button from Orasund/elm-ui-widgets, font color calculated using [the `accessibleTextColor` function](https://github.com/Orasund/elm-ui-widgets/blob/b509e632735cd58fdedb7fc59c72e2044f3864cd/src/Widget/Style/Material.elm#L292)
- **Material IO:** Elm UI button, font color according to [Material Design color picker](https://material.io/design/color/the-color-system.html#tools-for-picking-colors) starting from primary color `#0088ce`
- **Max Contrast:** Elm UI button, font color calculated using [`Color.Accessibility.maximumContrast` function](https://github.com/noahzgordon/elm-color-extra/blob/60e9c3be28e34129f3e11ec7e826bc337666fe60/src/Color/Accessibility.elm#L77) in the `noahzgordon/elm-color-extra`  package

## Summary

Ideally we can override the font color somehow. In the cases when we don't want to override the font color it would be preferable to use the same calculation as Material Design.

Thanks!

**Comment by Orasund** [comment]
There are a few different things going on here:

The Ratio between background and Font color is definied by the WCAG20 (and implemented by Color.Accessibility.maximumContrast). Legaly you are required to provide at least a ratio of 4.5:1, large Text(depending on context 14-18px) may have a ratio of 3:1. Recommended is a Contrast of at least 7:1 with large text at 4.5:1.

Material Design only has Black and White as Font colors and it chooses automatically which color to use, depending on the contrast. To do so, it calculate the minimal opacity for the -on color. and flips the font color if the opacity is below. The noteworthy thing here is that i do not know HOW it calculates the minimal opacity and what contrast ratio it uses.

It seams like Color.Accessibility.maximumContrast is always picking the color with the highest ratio, where as I will use black as long as the ratio is higher then 7:1.

---

Based on the image comparing material IO, max Contrast and my version, it seems like I should apply the same behaviour as maximumContrast.

**Comment by Orasund** [comment]
Bug is fixed in version 2.0.4 that just released. If this bug continues, please open a new issue.

Thanks again for pointing this out and for this wonderful and detailed description of the problem. Without it clearly would have been a lot harder to fix.

**Comment by julianpistorius** [comment]
Thank you for the quick fix @Orasund!

**Comment by c-mart** [comment]
I solved Problem 1 above with this little hack: use a `Widget.iconButton` instead of a `Widget.button`.

The "icon" can be any `Element.Element`, including text that you specify the color of. [Here's an ellie](https://ellie-app.com/bLCbvmWy6SFa1) demonstrating this (including some poor choices, granted!).

```
Widget.iconButton (primaryButtonStyle color)
    { text = "foobarbaz this is only shown to a screen reader?"
    , icon =
        Element.row
            []
            [ Element.el
                [ Element.Font.color (elmUiColor <| Color.rgb255 255 255 255) ]
                (Element.text "overridden")
            ]
    , onPress = ...
    }
```
