### ISSUE TITLE
Make it possible to force the rendering of a layout's menu as sidebar

### ISSUE THREAD

**Issue by kephas** [Orasund/elm-ui-widgets#15]
Currently, in `Widget.Layout.view` the code chooses if the menu should be a sidebar, if the device is a `Phone` or `Tablet` or if there are more than 5 elements in the menu. But someone might want a shorter menu as a sidebar anyway.

**Comment by Orasund** [comment]
The entire `Widget.Layout` code is very old and not very modular. It will definitely NOT stick around in Version 3 whenever that comes around. The Issue discussing the Layout rewrite is #8.

My suggestion would be to copy the `Widget.Layout` file into your own project and adjust it to your likings.
