### ISSUE TITLE
get MODULE NOT FOUND  import FeatherIcons when running example  

### ISSUE THREAD

**Issue by Delli** [Orasund/elm-ui-widgets#25]
Hi there ,  what I am doing wrong ?  
I cloned the repo (   like to add widgets ) 
then run  elm reactor.
on elm-ui-widgets-master\example\src\Example\Button.elm
elm gives me MODULE NOT FOUND  import FeatherIcons 
but in elm.json  there is  "feathericons/elm-feather": "1.4.0",  
what did I miss ?

**Comment by Orasund** [comment]
Have you run `elm reactor` within the `example` folder? This should to the trick.
I also noticed a different bug within the example folder, so please pull the new master branch.

**Comment by Orasund** [comment]
I'll close the issue now, if you still have problems, please open a new issue.
