### ISSUE TITLE
Name Space Collision

### ISSUE THREAD

**Issue by GaryBozek** [Orasund/elm-ui-widgets#26]
I was testing how to implement my own color palette and found a potential name collision.  This may not have existed before the V 2.2.0 Commit.

The /Widget/Style/Material.elm module uses avh4/elm-color as the type in Palette.  When I defined my own Palette to override in a module that already imported Color from elm-ui package (Element), it would not compile.
```
myDefaultPalette : Material.Palette
myDefaultPalette = 

    { primary    = rgb255  44  44  44       -- grey
    , secondary = .....
        : 
        : 
```

There are workarounds:
1.  Separate the elm-ui and elm-ui-widgets code into separate modules
2.  To use both elm-ui and elm-ui-widgets in the same module:
     - elm install avh4/elm-color
     - ```import Color  as Avh4Color```
     - use:   ```{ primary    = Avh4Color.rgb255  44  44  44       -- grey```

I point this out since this package explicitly targets users of elm-ui.  If an existing code base utilizes Color from elm-ui package, there may be potential issues.

**Comment by Orasund** [comment]
Closed, as this is not an issue.

Use `Color.rgb255` and `Element.rgb255` respectively.

`Color.Color` should be the preferred over `Element.Color`, but as you can see there is no name space collision.

For more info checkout the [corresponding issue over at Elm-Ui](https://github.com/mdgriffith/elm-ui/issues/28)
