### ISSUE TITLE
Some links in documentation not functional

### ISSUE THREAD

**Issue by dennistruemper** [Orasund/elm-ui-widgets#50]
Hi, I just want to let you know, some links on https://package.elm-lang.org/packages/Orasund/elm-ui-widgets/latest/?utm_campaign=Elm%20Weekly&utm_medium=email&utm_source=Revue%20newsletter do not work. 

Examples I found:
[Material Design Theme](/Widget-Material)
[Widget.Customize](/Widget-Customize)

**Comment by Orasund** [comment]
Thanks
