### ISSUE TITLE
UrlChange in Explorer not working

### ISSUE THREAD

**Issue by Orasund** [Orasund/elm-ui-widgets#66]
@cdevienne Changing the Url and then updating the page will result in an 500 Error. On localhost there are workarounds for it, but on Github.io this behaviour can't be changed (I've seen this problem pop up before). I like to have links that I can reference in the documentation.

I therefore suggest changing the path from `/Button` to `?page=Button`.

**Comment by cdevienne** [comment]
I am conflicted about this, I really prefer clean urls. But the hosting issue is a serious reason for a workaround.
https://github.com/rafgraph/spa-github-pages might be an option, if not your solution is the way to go.

**Comment by Orasund** [comment]
That works!
