### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by lukasturcani** [Orasund/elm-ui-widgets#83]
Hi there! Firstly I wanted to thank you for this amazing library! If you enable sponsoring to the repo, I would definitely like to send you some $$$ as a thank you.

I don't want to flood your repo with a bunch of issues, so I'm going to put them in this post and then split them out if that's what you prefer. 

At the moment the "master" branch (commit `a1fc9147d714c4a8056e3cac18c56a6a039ab5fa`) does not compile. There are a couple reasons for this, some of which are easy to fix and some less so. I've got a bunch of them here. The contributing guide says to make an issue before opening PRs, so let me know if you are happy for me to open PRs and if I should put all of of these fixes into one big PR or multiple small ones.

- In `src/Internal/Material/TextInput.elm`:  `import Element` needs to be `import Element exposing (Attribute)` because of the following type signature `textInputAttributes : Palette ->  List (Attribute msg)`
- In `src/Internal/TextInput.elm`:  `
import Element.Input as Input exposing (Placeholder)` needs to be `import Element.Input as Input exposing (Label, Placeholder)` because the type signature of the `internal` function uses it.
- In `src/Widget.elm`: `import Internal.Material.Palette exposing (Palette)` needs to be added because of the functions `usernameInput`, `emailInput`, `searchInput`, `spellCheckedInput` use it.

I'm also a little bit confused about the`usernameInput`, `emailInput` and `searchInput` functions. For example, the type signature of `usernameInput` is `Palette -> TextInputStyle msg`. This is very similar to the type signatures in the `Widget.Material` module, rather than in the `Widget` module. I'm guessing these should be moved from `src/Widget.elm` into the appropriate `Internal` and `Material` modules? I also think that the implementation of these methods is incomplete as they lead to type errors, so I am happy to try and fix them as well.

Apologies if I got any of these wrong!

**Comment by Orasund** [comment]
Thanks for pointing this out, ill check it sometime next week.

Lukas Turcani ***@***.***> schrieb am Fr., 17. Dez. 2021,
21:12:

**Comment by Orasund** [comment]
Should now be stable again.
