### ISSUE TITLE
CI failures

### ISSUE THREAD

**Issue by lukasturcani** [Orasund/elm-ui-widgets#86]
When opening a PR from a fork, the CI does not run, see: 

https://github.com/Orasund/elm-ui-widgets/actions/runs/1599340740

As far as I can tell, the solution is described here:

https://github.community/t/checkout-v2-error-actions-in-this-workflow-must-within-a-repository-owned-by-organization/136315/2

The CI also does not work in my own repo:

https://github.com/lukasturcani/elm-ui-widgets/runs/4575950188?check_suite_focus=true

I think the reasons are as follows:

* There is no `package-lock.json` in the root of `elm-ui-widgets`

**Comment by Orasund** [comment]
Yeah, it's the package-lock.json. Please don't be bothered by the CI failing. I will fix it in the near future

**Comment by lukasturcani** [comment]
Oh also, https://github.com/Orasund/elm-ui-widgets/blob/ae2b811683c702c34caed79b0ceb47e14b60602b/.github/workflows/main.yml#L6 - lists the branch as "main" but I think it should be "master"

**Comment by Orasund** [comment]
Master Branch is green.
