### ISSUE TITLE
Confusing msgMapper in Ellie examples

### ISSUE THREAD

**Issue by c-mart** [Orasund/elm-ui-widgets#9]
This is not a problem with the library per se, more a request for some explanation regarding its usage. In many of the Ellie examples, even the simple ones like [Button](https://ellie-app.com/8XDrHsxYkKNa1), there is a `msgMapper` pattern. The `identity` function is passed in from the main function, through the view, to the Widget being used.

@julianpistorius and I are having trouble understanding why this pattern is used/needed, and how it works. When we try to avoid using it, we get trapped in a mess of compiler errors related to type annotations. [Here](https://ellie-app.com/9mYWFMQYCZna1) is an example of what happens when you try to take the `msgMapper` out of the `Widget.button` example.

We have been using elm-ui in [Exosphere](https://gitlab.com/exosphere/exosphere/) for a long time and are only now seeing this for the first time. Any links to related information would also be appreciated.

Thank you!

**Comment by Orasund** [comment]
Sorry for your troubles, that shouldn't have happend.

On line 56 replace `msg` with `Msg` to make the Ellie code work.

The `msgMapper` is used to make the same code work on the website as well as in the Ellie.

The msgMapper is typically used to pass messages upwards. In Ellie its is not really needed so i just pass in the identity.
