### ISSUE TITLE
Can't Customize button: code snippet in doc not working

### ISSUE THREAD

**Issue by axelbdt** [Orasund/elm-ui-widgets#91]
Hi,
I encountered the following issue while trying the code snipped on top of the [Widget.Customage page](https://package.elm-lang.org/packages/Orasund/elm-ui-widgets/latest/Widget-Customize):
```
-- TYPE MISMATCH --------------- /home/axel/dev/elm-ui-widget-experimentation/src/Main.elm

This function cannot handle the argument sent through the (|>) pipe:

29|         (Material.containedButton
30|             |> Customize.element [ Element.width Element.fill ]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The argument is:

    Material.Palette -> Internal.Button.ButtonStyle msg

But (|>) is piping it to a function that expects:

    { a | element : List (Attribute msg) }
```
[Here is a repo where I produced the bug](https://github.com/axelbdt/elm-ui-widget-experimentation/blob/main/src/Main.elm).

Cheers

**Comment by Orasund** [comment]
the error tells you, that you are missing a Palette.
